# Generated by Django 2.2.3 on 2019-07-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190724_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
